# Generated by Django 3.2.25 on 2025-05-28 00:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=100)),
                ('track_name', models.CharField(blank=True, default='', max_length=100)),
                ('genre_name', models.CharField(choices=[('Rock', 'Rock'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('R&B', 'R&B')], max_length=100)),
            ],
            managers=[
                ('Tracks', django.db.models.manager.Manager()),
            ],
        ),
    ]
