# Generated by Django 3.2.25 on 2025-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='track',
            managers=[
            ],
        ),
    ]
