# Generated by Django 3.2.25 on 2025-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0002_auto_20250606_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='favtrack',
            name='price',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
